# Use root/example as user/password credentials
version: '3.1'

services:

  melusinedb:
    image: mysql:5.7
    container_name: melusinedb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: melusine
    ports:
      - 3306:3306
    volumes:
      - melusinedb-data:/var/lib/mysql

volumes:
  melusinedb-data:
