# Use root/example as user/password credentials
version: '3.1'

services:

  melusinedb:
    image: mariadb:latest
    platform: linux/arm64/v8
    container_name: melusinedb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: melusine
    ports:
      - 3306:3306
    volumes:
      - melusinedb-data:/var/lib/mysql

  react-app:
    image: node:14
    platform: linux/arm64
    container_name: react-app-container
    restart: unless-stopped
    working_dir: /app
    command: npm start
    volumes:
      - ../../front/melusine-frontend:/app
    ports:
      - "3000:3000"

volumes:
  melusinedb-data:
