spring.datasource:
  url: jdbc:mysql://localhost:3306/melusine
  username: root
  password: root
  initialization-mode: never
  sqlScriptEncoding: UTF-8

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  generate-ddl: true
  hibernate.ddl-auto: none
  show-sql: false

spring.mail:
  host: localhost
  port: 1025
  username: root
  password: root
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true

melusine.jwt:
  issuer: fr.polytech
  sign-key: kgCBXKmroU9Y3zVYmEBY8IdHuVJEXF5XNLWY7zy1Q7WVDt1PYLHtx1s5qpoH
  header-name: Authorization
  time-to-live: 36000

melusine.path:
  base: /tmp